Server complete
Alexithemia/HTTP-Socket-Server pull request #1
Opened 2019-01-23 00:09 UTC by Alexithemia

2019-01-26 21:24 UTC, taesup requested changes

2019-01-26 21:24 UTC, taesup commented on client.js
> +  } else {
So there could be an issue where if someone tried to use an option that this client does support at the end of the command. Then that last option will end up being the url.

2019-01-26 21:24 UTC, taesup commented on client.js
> +    if (methods[process.argv[i]]) {
So curl has a flag for setting the method, I believe it's -X, so it's best to re-write this to follow that convention.

2019-01-26 21:24 UTC, taesup commented on server.js
> +  return fs.readFileSync(filePath);
Sync based methods are not allowed.

2019-01-29 19:41 UTC, jhoun commented
LGTM:white_check_mark:

2019-01-31 20:48 UTC, merged